packages:
  - "apps/**"
  - "internal/**"
  - "packages/**"

nodeVersion: "26.2.0"
engineStrict: true

linkWorkspacePackages: true
saveWorkspaceProtocol: "rolling"
savePrefix: ""

publicHoistPattern:
  - "*eslint*"
  - "*@eslint*"
  - "*prettier*"
  - "*lint-staged*"
  - "*stylelint*"
  - "*commitlint*"
  - "*@commitlint*"
  - "*cz*"
  - "*simple-git-hooks*"
  - "*changeset*"

catalog:
  "@types/node": "^26.0.1"
  "npm-run-all2": "^9.0.2"
  "rimraf": "^6.1.3"
  "typescript": "^6.0.3"
  "zod": "^4.4.3"
  "dayjs": "^1.11.21"
  "vite": "^8.1.0"

catalogs:
  "dx":
    "eslint": "^10.6.0"
    "@sxzz/eslint-config": "^8.2.1"
    "@commitlint/cli": "^21.1.0"
    "@commitlint/config-conventional": "^21.1.0"
    "@commitlint/types": "^21.1.0"
    "czg": "^1.13.1"
    "lint-staged": "^17.0.8"
    "prettier": "^3.9.2"
    "simple-git-hooks": "^2.13.1"
    "@unconfig/ts-config": "^0.1.11"
    "@unconfig/changeset-workflow": "^0.0.3"
    "@changesets/changelog-github": "^0.7.0"
    "tsdown": "^0.22.3"
    "tsx": "^4.22.4"
    "turbo": "^2.9.14"
    "@manypkg/get-packages": "^3.1.0"
  "test":
    "vitest": "^4.1.8"
    "@vitest/ui": "^4.1.8"
    "@vitest/coverage-v8": "^4.1.8"
    "jsdom": "^29.1.1"

allowBuilds:
  esbuild: true
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - "@unconfig/changeset-workflow@0.0.2 || 0.0.3"
  - "@unconfig/ts-config@0.1.11"
