import { HTTP_STATUS_CODES } from "@unimolecule/canon/http-status-codes";
import type { KnownStatusCode } from "./types";

export const STATUS_MESSAGES = {
  BAD_REQUEST: HTTP_STATUS_CODES.BAD_REQUEST.phrase,
  UNAUTHORIZED: HTTP_STATUS_CODES.UNAUTHORIZED.phrase,
  FORBIDDEN: HTTP_STATUS_CODES.FORBIDDEN.phrase,
  NOT_FOUND: HTTP_STATUS_CODES.NOT_FOUND.phrase,
  METHOD_NOT_ALLOWED: HTTP_STATUS_CODES.METHOD_NOT_ALLOWED.phrase,
  REQUEST_TIMEOUT: HTTP_STATUS_CODES.REQUEST_TIMEOUT.phrase,
  TOO_MANY_REQUESTS: HTTP_STATUS_CODES.TOO_MANY_REQUESTS.phrase,
  INTERNAL_SERVER_ERROR: HTTP_STATUS_CODES.INTERNAL_SERVER_ERROR.phrase,
  NOT_IMPLEMENTED: HTTP_STATUS_CODES.NOT_IMPLEMENTED.phrase,
  BAD_GATEWAY: HTTP_STATUS_CODES.BAD_GATEWAY.phrase,
  SERVICE_UNAVAILABLE: HTTP_STATUS_CODES.SERVICE_UNAVAILABLE.phrase,
  GATEWAY_TIMEOUT: HTTP_STATUS_CODES.GATEWAY_TIMEOUT.phrase,
  HTTP_VERSION_NOT_SUPPORTED:
    HTTP_STATUS_CODES.HTTP_VERSION_NOT_SUPPORTED.phrase,
} as const;

export const STATUS_MESSAGE_BY_CODE = {
  [HTTP_STATUS_CODES.BAD_REQUEST.code]: STATUS_MESSAGES.BAD_REQUEST,
  [HTTP_STATUS_CODES.UNAUTHORIZED.code]: STATUS_MESSAGES.UNAUTHORIZED,
  [HTTP_STATUS_CODES.FORBIDDEN.code]: STATUS_MESSAGES.FORBIDDEN,
  [HTTP_STATUS_CODES.NOT_FOUND.code]: STATUS_MESSAGES.NOT_FOUND,
  [HTTP_STATUS_CODES.METHOD_NOT_ALLOWED.code]:
    STATUS_MESSAGES.METHOD_NOT_ALLOWED,
  [HTTP_STATUS_CODES.REQUEST_TIMEOUT.code]: STATUS_MESSAGES.REQUEST_TIMEOUT,
  [HTTP_STATUS_CODES.TOO_MANY_REQUESTS.code]: STATUS_MESSAGES.TOO_MANY_REQUESTS,
  [HTTP_STATUS_CODES.INTERNAL_SERVER_ERROR.code]:
    STATUS_MESSAGES.INTERNAL_SERVER_ERROR,
  [HTTP_STATUS_CODES.NOT_IMPLEMENTED.code]: STATUS_MESSAGES.NOT_IMPLEMENTED,
  [HTTP_STATUS_CODES.BAD_GATEWAY.code]: STATUS_MESSAGES.BAD_GATEWAY,
  [HTTP_STATUS_CODES.SERVICE_UNAVAILABLE.code]:
    STATUS_MESSAGES.SERVICE_UNAVAILABLE,
  [HTTP_STATUS_CODES.GATEWAY_TIMEOUT.code]: STATUS_MESSAGES.GATEWAY_TIMEOUT,
  [HTTP_STATUS_CODES.HTTP_VERSION_NOT_SUPPORTED.code]:
    STATUS_MESSAGES.HTTP_VERSION_NOT_SUPPORTED,
} as const satisfies Record<KnownStatusCode, string>;
