import type { HTTP_STATUS_CODES } from "@unimolecule/canon/http-status-codes";

export type KnownStatusCode =
  | typeof HTTP_STATUS_CODES.BAD_REQUEST.code
  | typeof HTTP_STATUS_CODES.UNAUTHORIZED.code
  | typeof HTTP_STATUS_CODES.FORBIDDEN.code
  | typeof HTTP_STATUS_CODES.NOT_FOUND.code
  | typeof HTTP_STATUS_CODES.METHOD_NOT_ALLOWED.code
  | typeof HTTP_STATUS_CODES.REQUEST_TIMEOUT.code
  | typeof HTTP_STATUS_CODES.TOO_MANY_REQUESTS.code
  | typeof HTTP_STATUS_CODES.INTERNAL_SERVER_ERROR.code
  | typeof HTTP_STATUS_CODES.NOT_IMPLEMENTED.code
  | typeof HTTP_STATUS_CODES.BAD_GATEWAY.code
  | typeof HTTP_STATUS_CODES.SERVICE_UNAVAILABLE.code
  | typeof HTTP_STATUS_CODES.GATEWAY_TIMEOUT.code
  | typeof HTTP_STATUS_CODES.HTTP_VERSION_NOT_SUPPORTED.code;
