import { HTTP_STATUS_CODES } from "./status-codes";

export const RESPONSE_SUCCESS_CODE = HTTP_STATUS_CODES.OK.code;
export const RESPONSE_SUCCESS_MESSAGE = HTTP_STATUS_CODES.OK.phrase;
export const RESPONSE_SUCCESS_OK = true;

export const RESPONSE_ERROR_CODE = HTTP_STATUS_CODES.INTERNAL_SERVER_ERROR.code;
export const RESPONSE_ERROR_MESSAGE =
  HTTP_STATUS_CODES.INTERNAL_SERVER_ERROR.phrase;
export const RESPONSE_ERROR_OK = false;
